# Generated by Django 5.0.4 on 2024-04-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="React",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=80)),
                ("lastname", models.CharField(max_length=80)),
                ("email", models.CharField(max_length=80)),
            ],
        ),
    ]
